#--------------------------------Mongo Database------------------------#
#----------------------------Network: data-app-nwt---------------------#
version: '3'
services:
  mongodb:
    image: mongo
    networks:
      - data-app-nwt
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    depends_on: 
      - mongodb
    networks: 
      - data-app-nwt
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
networks:
  data-app-nwt:
    external: true
